# Generated by Django 3.2.7 on 2021-09-02 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPrepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=100)),
                ('tid', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=100)),
                ('sid', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_order_id', models.CharField(max_length=100)),
                ('payment_mothod_type', models.CharField(max_length=100)),
                ('amount', models.JSONField()),
                ('card_info', models.JSONField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('approved', models.DateTimeField()),
                ('partner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
