# Generated by Django 3.2.7 on 2021-09-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_item_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_mothod_type',
            new_name='payment_method_type',
        ),
    ]
